<?php
header('Content-type: text/html');
header('Access-Control-Allow-Origin: *');

$allProducts = array (
  array (
    'price' => '14',
    'shipping' => 0,
    'pdescription' => 'RED/M',
    'external_id' => '110173691466',
    'product_code' => '8000000C-1495098928',
    'limit_qty' => '73',
    'unlimited_stock' => 'No',
    'pname' => '1 variable test update-RED-M-R',
    'pid' => '1',
    'taxable' => 'Yes',
    'dir_path' => 'images/',
    'img_name' => 'placeholder.png',
    'attributes' => '{"Color":[{"price":0,"name":"Red"},{"price":0,"name":"Blue"},{"price":0,"name":"Green"}],"Size":{"3":{"price":0,"name":"Small"},"4":{"price":0,"name":"Medium"},"5":{"price":0,"name":"Large"}}}',
    'weight' => '0',
    'length' => '0',
    'width' => '0',
    'height' => '0',
    'product_type' => 'straight',
    'pro_limit_purchase' => '0',
  ),
  array (
    'price' => '90',
    'shipping' => 0,
    'pdescription' => 'testst',
    'external_id' => '',
    'product_code' => '8000001F-1495363975',
    'limit_qty' => '-9',
    'unlimited_stock' => 'No',
    'pname' => '7 Brass Ouroboros Ring(OBB)',
    'pid' => '7',
    'taxable' => 'No',
    'dir_path' => 'images/',
    'img_name' => 'placeholder.png',
    'attributes' => '[]',
    'weight' => '0',
    'length' => '0',
    'width' => '0',
    'height' => '0',
    'product_type' => 'straight',
    'pro_limit_purchase' => '0',
  ),
  array (
    'price' => '90',
    'shipping' => 0,
    'pdescription' => 'RED/M',
    'external_id' => '096619756803',
    'product_code' => '80000007-1475840688',
    'limit_qty' => '-17',
    'unlimited_stock' => 'Yes',
    'pname' => 'Brass Ouroboros Ring(OBR)',
    'pid' => '2',
    'taxable' => 'Yes',
    'dir_path' => 'images/',
    'img_name' => 'placeholder.png',
    'attributes' => '[]',
    'weight' => '0',
    'length' => '0',
    'width' => '0',
    'height' => '0',
    'product_type' => 'straight',
    'pro_limit_purchase' => '0',
  ),
  array (
    'price' => '100',
    'shipping' => 0,
    'pdescription' => 'RED/M',
    'external_id' => '',
    'product_code' => '80000008-1475840690',
    'limit_qty' => '-2',
    'unlimited_stock' => 'Yes',
    'pname' => 'Brass Ouroboros Ring(OBE)',
    'pid' => '3',
    'taxable' => 'Yes',
    'dir_path' => 'images/',
    'img_name' => 'placeholder.png',
    'attributes' => '[]',
    'weight' => '0',
    'length' => '0',
    'width' => '0',
    'height' => '0',
    'product_type' => 'straight',
    'pro_limit_purchase' => '0',
  ),
  array (
    'price' => '90',
    'shipping' => 0,
    'pdescription' => 'RED/M',
    'external_id' => '',
    'product_code' => '8000000C-1476442389',
    'limit_qty' => '0',
    'unlimited_stock' => 'Yes',
    'pname' => 'Brass Ouroboros Ring(OBC)',
    'pid' => '4',
    'taxable' => 'Yes',
    'dir_path' => 'images/',
    'img_name' => 'placeholder.png',
    'attributes' => '[]',
    'weight' => '0',
    'length' => '0',
    'width' => '0',
    'height' => '0',
    'product_type' => 'straight',
    'pro_limit_purchase' => '0',
  ),
  array (
    'price' => '90',
    'shipping' => 0,
    'pdescription' => 'RED/M',
    'external_id' => '',
    'product_code' => '8000000D-1476442390',
    'limit_qty' => '0',
    'unlimited_stock' => 'Yes',
    'pname' => 'le derm direct upsell',
    'pid' => '5',
    'taxable' => 'Yes',
    'dir_path' => 'images/',
    'img_name' => 'placeholder.png',
    'attributes' => '[]',
    'weight' => '0',
    'length' => '0',
    'width' => '0',
    'height' => '0',
    'product_type' => 'straight',
    'pro_limit_purchase' => '0',
  ),
  array (
    'price' => '90',
    'shipping' => 0,
    'pdescription' => 'RED/M',
    'external_id' => 'T112703593',
    'product_code' => '8000000E-1476442391',
    'limit_qty' => '0',
    'unlimited_stock' => 'Yes',
    'pname' => 'Brass Ouroboros Ring(OBW)',
    'pid' => '6',
    'taxable' => 'Yes',
    'dir_path' => 'images/',
    'img_name' => 'placeholder.png',
    'attributes' => '[]',
    'weight' => '0',
    'length' => '0',
    'width' => '0',
    'height' => '0',
    'product_type' => 'straight',
    'pro_limit_purchase' => '0',
  ),
  array (
    'price' => '60',
    'shipping' => 0,
    'pdescription' => 'testst',
    'external_id' => '',
    'product_code' => '80000010-1476442394',
    'limit_qty' => '1',
    'unlimited_stock' => 'No',
    'pname' => 'Brass Ouroboros Ring(OBN)',
    'pid' => '8',
    'taxable' => 'Yes',
    'dir_path' => 'images/',
    'img_name' => 'placeholder.png',
    'attributes' => '[]',
    'weight' => '0',
    'length' => '0',
    'width' => '0',
    'height' => '0',
    'product_type' => 'straight',
    'pro_limit_purchase' => '0',
  ),
  array (
    'price' => '1',
    'shipping' => 0,
    'pdescription' => 'testst',
    'external_id' => '',
    'product_code' => '80000004-1482746083',
    'limit_qty' => '1',
    'unlimited_stock' => 'No',
    'pname' => 'Fraud Check 9',
    'pid' => '9',
    'taxable' => 'Yes',
    'dir_path' => 'images/',
    'img_name' => 'placeholder.png',
    'attributes' => '[]',
    'weight' => '0',
    'length' => '0',
    'width' => '0',
    'height' => '0',
    'product_type' => 'straight',
    'pro_limit_purchase' => '0',
  ),
  'total' => 9,
);

echo json_encode($allProducts);
?>